### ISSUE TITLE
Unable to connect to Druid cluster that has CACert enabled; no way to pass a certificate

### ISSUE THREAD

**Issue by dleybz** [grafadruid/druid-grafana#71]
I'm attempting to connect to a Druid cluster that uses both basic auth and CA cert. I see that there's a way to pass the username and pass, but no way to pass a cert. How can I enable connectivity between the Druid cluster and Grafana?

**Comment by jbguerraz** [comment]
Hello @dleybz !
Thank you for your report.
The plugin doesn't provide any support for X509 authentication, however, Druid doesn't looks to support it neither (https://druid.apache.org/docs/latest/design/auth.html).
If you're about providing a, custom, CA cert in order to validate a self-signed TLS certificate for HTTPS usage then the plugin doesn't support that neither but now provide an option to skip verifying the TLS certificate (thx @raakasf : https://github.com/grafadruid/druid-grafana/pull/51 ).
That being said the current master is in trouble since the go-druid v0.0.3 introduced a breaking change that isn't yet covered by this grafana plugin (but not for long! a refactor gonna land pretty soon in master and will provide that required support).
Feel free to join us on Slack so we can help you further with any kind of setup you have!

**Comment by jbguerraz** [comment]
@dleybz This is supposed to be fine by now. I'll close that issue. If the problem persist, feel free to join us on Slack or open a new issue :) thank you!
