### ISSUE TITLE
How Can I Set Timezone?

### ISSUE THREAD

**Issue by dev-hana** [grafadruid/druid-grafana#85]
![image](https://user-images.githubusercontent.com/46733911/119309265-0982e400-bca9-11eb-8cfc-5fb4dd8ee32d.png)
This is in Druid

![image](https://user-images.githubusercontent.com/46733911/119309376-2ddec080-bca9-11eb-8877-b50a24997df0.png)
This is in Grafana

**Comment by jbguerraz** [comment]
Hello @dev-hana 
Druid stores the time as UTC 0 (hence the "Z" at the end of the datetime), Grafana on its side shows you the date in your own timezone, here UTC +9 since you're in Seoul.
If you want to change your timezone on Grafana (to make it UTC 0 for you as well for instance) side you can have a look there: https://grafana.com/docs/grafana/latest/administration/preferences/change-grafana-timezone/

You could also be interested in https://druid.apache.org/docs/latest/querying/sql.html#time-functions and https://druid.apache.org/docs/latest/misc/math-expr.html#time-functions (in pair with https://druid.apache.org/docs/latest/querying/virtual-columns.html) even if for regular use cases I wouldn't recommend it.

Feel free to close that issue if you believe it's all fine now :)
