### ISSUE TITLE
help to create a group by querie

### ISSUE THREAD

**Issue by philippesg** [grafadruid/druid-grafana#90]
Hello, we used to use the first druid plugin for Grafana (https://github.com/societe-generale/druidplugin ) and as you can see when we do a group by (or topn) query , Druid give us 2 metrics : one for each series

![image](https://user-images.githubusercontent.com/49228865/120806299-fb558300-c546-11eb-9e99-741f4218fb70.png)

When we try do to the same with your plugin, the asnwer is only one metric instead of 2, when we used the graph panel. We don't understand why because when we do the same query with a table panel panel, we can see all the data. For example : 

![image](https://user-images.githubusercontent.com/49228865/120808841-c4cd3780-c549-11eb-9f93-2451a6727a40.png)

![image](https://user-images.githubusercontent.com/49228865/120806627-6010dd80-c547-11eb-807f-cabed54fd8e9.png)

![image](https://user-images.githubusercontent.com/49228865/120806645-6606be80-c547-11eb-91bc-f0d6556a156a.png)

![image](https://user-images.githubusercontent.com/49228865/120807016-cb5aaf80-c547-11eb-9ce3-f0ba78b83f6b.png)

![image](https://user-images.githubusercontent.com/49228865/120807041-d0b7fa00-c547-11eb-960c-49aea8682f7c.png)

Best regards.

**Comment by jbguerraz** [comment]
Hello @philippesg 

Thank you!

Could it be that the response is "long" formatted instead of "wide"? (related: https://grafana.com/docs/grafana/latest/developers/plugins/data-frames/#data-frames-as-time-series )

To adjust the format, you may check it out:

![image](https://user-images.githubusercontent.com/861556/120841837-86407880-c55b-11eb-96bf-6bb3e1606df6.png)

Hope that helps!

NB: we could eventually default the format to "wide" (since it's probably most used) instead of long (here: https://github.com/grafadruid/druid-grafana/blob/master/pkg/druid.go#L750)

**Comment by philippesg** [comment]
Hello @jbguerraz ,  it's exactly the problem, i changed the format to "wide" instead of long and i'm seeing the 2 series of data. 
Thank very much.
