### ISSUE TITLE
Granularity variable ?

### ISSUE THREAD

**Issue by philippesg** [grafadruid/druid-grafana#92]
Hello, how to use variable in the granularity field with the builder query because my users want to chose the granularity themselve ?

**Comment by jbguerraz** [comment]
Maybe there is a chance by using the query type "json" and adding the variable there.
Ideally we would allow to create entry in the select box directly and so we could type a variable there.
Let's keep this issue open even if the "json workaround" works well so we can provide this enhacement (+ if you're willing to contribute, you're more than welcome! :) join us on slack!)

**Comment by philippesg** [comment]
Hello @jbguerraz . Yes, i tried this workound and it worked well. 
But as you can see below, the builder show 'simple' instead of the variable :
![granularity-2](https://user-images.githubusercontent.com/49228865/122521122-bd5f6100-d014-11eb-8d22-03ccd37378aa.JPG)
![granularity-1](https://user-images.githubusercontent.com/49228865/122521092-b59fbc80-d014-11eb-98e3-8c84648dc733.JPG)
Best regards.

**Comment by jbguerraz** [comment]
Hello,

Yep, that's expected. BTW, I believe you don't need the `:druid:json` formatter here, probably just `${granS}` since that is not a multiple value variable.
We probably should implement https://developers.grafana.com/ui/latest/index.html?path=/story/forms-select--custom-value-creation on https://github.com/grafadruid/druid-grafana/blob/master/src/builder/abstract/Select.tsx (maybe using a prop to enable/disable it as well).
If you will to contribute it, I'll be happy to help, join me on https://join.slack.com/t/grafadruid/shared_invite/zt-ryrcolyp-GQCiKcOF0WhnK~iqpkrqLA

**Comment by jbguerraz** [comment]
@philippesg feel free to check #95  out! it actually fix that :) it's (for now at least) enabled for any select box and would accept any kind of option (not only variable). probably something to fine tune.
